name: "actions-timeline"
description: "Show workflow timeline in summary"
author: "kesin1202000@gmail.com"
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
runs:
  using: "node16"
  main: "dist/main.js"
  post: "dist/post.js"
