name: "actions-timeline"
description: "An Action shows timeline of a GitHub Action workflow in the run summary page."
author: "kesin1202000@gmail.com"
branding:
  icon: "activity"
  color: "blue"
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  show-waiting-runner:
    description: Show waiting runner time in the timeline.
    default: true
    required: false
runs:
  using: "node20"
  main: "dist/main.js"
  post: "dist/post.js"
