name: Setup Deno with cache
description: setup-deno with dependencies cache
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      with:
        path: ~/.cache/deno
        key: deno-${{ github.job }}-${{ runner.os }}-${{ hashFiles('deno.lock') }}
        restore-keys: |
          deno-${{ github.job }}-${{ runner.os }}-
    - name: Set .tool-versions to output
      id: tool-versions
      run: awk '{ print $1"="$2 }' .tool-versions >> $GITHUB_OUTPUT
      shell: bash
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v${{ steps.tool-versions.outputs.deno }}
