name: POC

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  mermaid_summary:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          cat gantt.md >> $GITHUB_STEP_SUMMARY
